package com.ituhn.pemkom2.gui;

import com.ituhn.pemkom2.gui.panel.Settings;
import com.ituhn.pemkom2.objects.Karyawan;
import com.ituhn.pemkom2.services.DigitalClockService;
import com.ituhn.pemkom2.services.I18nService;
import com.ituhn.pemkom2.services.KaryawanService;
import com.ituhn.pemkom2.services.LogAbsensiService;
import com.ituhn.pemkom2.services.SerialService;
import com.ituhn.pemkom2.util.EncryptionUtils;
import com.ituhn.pemkom2.util.SecurityUtils;
import java.util.Locale;
import javax.swing.JLabel;
import javax.swing.SwingUtilities;

/**
 *
 * @author mnish
 */
public class AttendancePage extends javax.swing.JFrame {

    // Referensi thread disimpan untuk ditrack jika dibutuhkan (misal: untuk stop/cek status)
    private Thread clockThread;

    Thread delayThread;

    /**
     * Creates new form AttendancePage
     */
    public AttendancePage() {
        I18nService.setLocale(Locale.of(Settings.prefs.get("LANGUAGE", Settings.statusLang))); 
        initComponents();

        initClock(jLabel1);
        jLabel7.setText(Settings.prefs.get("LAST_STATUS", Settings.statusAbsen));

        //inisialisasi thread delayThread
        updateLabelWithDelay(jLabel7, "");
        
        
        registerHandler();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        autoScaledLabel1 = new com.ituhn.pemkom2.palette.AutoScaledLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        rFIDIconPanel1 = new com.ituhn.pemkom2.palette.RFIDIconPanel();
        labeltap = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(226, 211, 188));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(104, 23, 39));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/calendar-clock-icon.png"))); // NOI18N
        jLabel1.setText(I18nService.get("ui.date.format")
        );

        autoScaledLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/uhn_logo.png"))); // NOI18N
        autoScaledLabel1.setText(".");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(autoScaledLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 318, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 400, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(31, 31, 31))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(autoScaledLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 88, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        getContentPane().add(jPanel1, java.awt.BorderLayout.PAGE_START);

        jPanel2.setBackground(new java.awt.Color(226, 211, 188));
        jPanel2.setPreferredSize(new java.awt.Dimension(1117, 40));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1117, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel2, java.awt.BorderLayout.PAGE_END);

        jPanel3.setLayout(new java.awt.GridBagLayout());

        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        javax.swing.GroupLayout rFIDIconPanel1Layout = new javax.swing.GroupLayout(rFIDIconPanel1);
        rFIDIconPanel1.setLayout(rFIDIconPanel1Layout);
        rFIDIconPanel1Layout.setHorizontalGroup(
            rFIDIconPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 60, Short.MAX_VALUE)
        );
        rFIDIconPanel1Layout.setVerticalGroup(
            rFIDIconPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );

        jPanel4.add(rFIDIconPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(216, 84, -1, -1));

        labeltap.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        labeltap.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labeltap.setText(I18nService.get("ui.welcome"));
        jPanel4.add(labeltap, new org.netbeans.lib.awtextra.AbsoluteConstraints(194, 41, 246, -1));

        jPanel5.setBackground(new java.awt.Color(102, 102, 102));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText(I18nService.get("ui.label.name"));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText(I18nService.get("ui.label.id"));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText(I18nService.get("ui.label.dept"));

        jLabel6.setBackground(new java.awt.Color(0, 204, 204));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Avatar");
        jLabel6.setOpaque(true);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 446, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel5))
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        jPanel4.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(31, 151, -1, -1));

        jLabel7.setBackground(new java.awt.Color(104, 23, 39));
        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("jLabel7");
        jLabel7.setOpaque(true);
        jPanel4.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(31, 255, 570, 90));

        jButton1.setText(I18nService.get("ui.btn.simulation"));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(294, 93, -1, -1));

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(61, 226, 71, 290);
        jPanel3.add(jPanel4, gridBagConstraints);

        getContentPane().add(jPanel3, java.awt.BorderLayout.CENTER);

        setSize(new java.awt.Dimension(1131, 625));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        SerialService.getInstance().broadcast("1555");
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(() -> {
            new AttendancePage().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.ituhn.pemkom2.palette.AutoScaledLabel autoScaledLabel1;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JLabel labeltap;
    private com.ituhn.pemkom2.palette.RFIDIconPanel rFIDIconPanel1;
    // End of variables declaration//GEN-END:variables

    private void initClock(JLabel lblJam) {
        DigitalClockService service = new DigitalClockService(lblJam, I18nService.get("ui.date.format"));
        clockThread = service.getThread();
        clockThread.setName("Thread-Jam-Kiosk");
        clockThread.setDaemon(true);
        clockThread.start();
    }

    private void registerHandler() {
        KaryawanService krService = new KaryawanService();
        LogAbsensiService logService = new LogAbsensiService();

        SerialService.getInstance().addHandler(dataRfid -> {
            String hashedUid = SecurityUtils.getHash(dataRfid, SecurityUtils.SHA_256);
            Karyawan k = krService.findByUid(hashedUid);
           
            SwingUtilities.invokeLater(() -> {
                if (k != null) {
                    logService.simpanLog(hashedUid, Settings.prefs.get("LAST_STATUS", Settings.statusAbsen));
                        jLabel3.setText(I18nService.get("ui.label.name")+": " + k.getNamaLengkap() + "");
                        jLabel4.setText(I18nService.get("ui.label.id")+": " + EncryptionUtils.decrypt(k.getIdKaryawan()));
                        jLabel5.setText(I18nService.get("ui.label.dept")+": " + k.getDepartemen());
                        updateLabelWithDelay(jLabel7, I18nService.get("ui.status.success"));
                } else {
                    updateLabelWithDelay(jLabel7, I18nService.get("ui.status.failed"));
                }
            });
        });
    }

    private void updateLabelWithDelay(JLabel comp, String info) {
        if (delayThread != null && delayThread.isAlive()) {
            delayThread.interrupt();
        }

        delayThread = new Thread(() -> {
            comp.setText(info); 
            try {
                for (int i = 3; i >= 1; i--) {
                    Thread.sleep(1000);
                }
                
                SwingUtilities.invokeLater(() -> comp.setText(Settings.prefs.get("LAST_STATUS", Settings.statusAbsen)));

            } catch (InterruptedException e) {
                // Penanganan jika thread dihentikan paksa (Interrupted)
            }
        });

        delayThread.setName("delayThread"); 
        delayThread.setDaemon(true);         
        delayThread.start();
    }

}
